translationEN = {
    // NAV LINKS
    "KEY_NAV_LINK_Board": "Board",
    "KEY_NAV_LINK_Budgets": "Budget",
    "KEY_NAV_LINK_Expenses": "Expenses",
    "KEY_NAV_LINK_Income": "Income",
    "KEY_NAV_LINK_Statistics": "Statistics",
    "KEY_NAV_LINK_Moneys": "Moneys",
    "KEY_NAV_LINK_Reports": "Reports",
    "KEY_NAV_LINK_Data": "My Data",
    "KEY_NAV_LINK_Configuration": "Configuration",
    "KEY_NAV_LINK_Close_Session": "Close Session",
    //TAB SUP
    "KEY_Main_Title": "Mains",
    "KEY_Main_Gastos_acum": "Accumulated expenses",
    "KEY_Main_Ingresos_acum": "Accumulated income",
    "KEY_Main_Presp_disp": "Available Budget",
    // BOARD
    "KEY_BOARD_Cant_Operac_Title": "Quantity Operations",
    "KEY_BOARD_Cant_Operac_Subtitle_income": "Income",
    "KEY_BOARD_Cant_Operac_Subtitle_expenses": "Expenses",
    "KEY_BOARD_Cant_Operac_Subtitle_expenses": "Expenses",
    "KEY_BOARD_SubsTitle": "Check the last information",
    // BUDGET
    "KEY_BUDGET_Name_Title": "Budget Name",
    "KEY_BUDGET_Date_Title": "Budget Date",
    "KEY_BUDGET_Index_Title": "Budget Index",
    "KEY_BUDGET_Clean_Title": "Clean Budget",
    "KEY_BUDGET_Empty_Title": "Empty Budget",
    // STATISTICS
    "KEY_STATISTICS_Quant_Expenses_Graph_Title": "Graphic amount of Expenses",
    "KEY_STATISTICS_Quant_Income_Graph_Title": "Income amount graph",
    "KEY_STATISTICS_Percentages_Expenses_Graph_Title": "Graph of income percentages",
    "KEY_STATISTICS_Percentages_Income_Graph_Title": "Income percentage graph",
    "KEY_STATISTICS_Price_Expenses_Graph_Title": "Income price graph",
    "KEY_STATISTICS_Price_Income_Graph_Title": "Income price graph",
    //MONEYS
    "KEY_MONEYS_Main_Title": "Moneys values",
    "KEY_MONEYS_Dolar_Title": "Dollar value",
    "KEY_MONEYS_Real_Title": "Real value",
    "KEY_MONEYS_Euro_Title": "Euro value",
    "KEY_MONEYS_Last_act_Title": "Last act.",
    "KEY_MONEYS_sold_Subtitle": "Sold :  ",
    "KEY_MONEYS_buy_Subtitle": "Buy :  ",
    "KEY_MONEYS_variation_Subtitle": "Variation :  ",
    //REPORTS
    "KEY_REPORTS_Main_title": "Reports",
    "KEY_REPORTS_Main_Subtitle": "Last reports information",
    "KEY_REPORTS_Download_report_title": "Download report",
    //DATA
    "KEY_DATA_Cat_title": "Categories",
    "KEY_DATA_Cat_Edit_subtitle": "Edit: ",
    "KEY_DATA_Cat_add_subtitle": "Add: ",
    "KEY_DATA_Payments_title": "Payment methods",
    "KEY_DATA_Payments_Edit_subtitle": "Edit: ",
    "KEY_DATA_Payments_add_subtitle": "Add: ",
    "KEY_DATA_Cards_title": "Credit Cards",
    "KEY_DATA_Cards_Edit_subtitle": "Edit: ",
    "KEY_DATA_Cards_add_subtitle": "Add: ",
    "KEY_DATA_Banks_title": "Banks",
    "KEY_DATA_Banks_Edit_subtitle": "Edit: ",
    "KEY_DATA_Banks_add_subtitle": "Add: ",
    //CONFIGURACION
    "KEY_CONFIGURATION_Languaje_title": "Languaje",
    "KEY_CONFIGURATION_Languaje_subtitle": "Selecct option",
    "KEY_CONFIGURATION_Theme_title": "Color",
    "KEY_CONFIGURATION_Theme_subtitle": "Selecct option",
    //INCOME
    "KEY_INCOME_Main_title": "Add",
    "KEY_INCOME_Add_item_subtitle": "Item: ",
    "KEY_INCOME_Add_value_subtitle": "Value: ",
    "KEY_INCOME_Add_cat_subtitle": "Category: ",
    "KEY_INCOME_Add_payment_subtitle": "Payment Method: ",
    "KEY_INCOME_Add_descrip_subtitle": "Description: ",
    "KEY_INCOME_Add_save_subtitle": "Save",
    "KEY_INCOME_Graph_Title": "Graph Incomes ",
    "KEY_INCOME_LastList_Title": "Recently ",
    "KEY_INCOME_CompleteList_Title": "Full Incomes list",
    //EXPENSES
    "KEY_EXPENSES_Main_title": "Add",
    "KEY_EXPENSES_Add_item_subtitle": "Item: ",
    "KEY_EXPENSES_Add_value_subtitle": "Value: ",
    "KEY_EXPENSES_Add_cat_subtitle": "Category:  ",
    "KEY_EXPENSES_Add_payment_subtitle": "Payment Method: ",
    "KEY_EXPENSES_Add_descrip_subtitle": "Description: ",
    "KEY_EXPENSES_Add_save_subtitle": "Save",
    "KEY_EXPENSES_Graph_Title": "Graph Incomes ",
    "KEY_EXPENSES_LastList_Title": "Recently ",
    "KEY_EXPENSES_CompleteList_Title": "Full Expenses list",
    //ERROR
    "KEY_ERROR_Title": "Page not found",

}