translationES = {
    // NAV LINKS
    "KEY_NAV_LINK_Board": "Tablero",
    "KEY_NAV_LINK_Budgets": "Presupuesto",
    "KEY_NAV_LINK_Expenses": "Gastos",
    "KEY_NAV_LINK_Income": "Ingresos",
    "KEY_NAV_LINK_Statistics": "Estadisticas",
    "KEY_NAV_LINK_Moneys": "Cotizaciones",
    "KEY_NAV_LINK_Reports": "Reportes",
    "KEY_NAV_LINK_Data": "Mis datos",
    "KEY_NAV_LINK_Configuration": "Configuracion",
    "KEY_NAV_LINK_Close_Session": "Cerrar sesion",
    //TAB SUP
    "KEY_Main_Title": "Principales",
    "KEY_Main_Gastos_acum": "Gastos acumulados",
    "KEY_Main_Ingresos_acum": "Ingresos acumulados",
    "KEY_Main_Presp_disp": "Presup. Disponible",
    // BOARD
    "KEY_BOARD_Cant_Operac_Title": "Cantidad de operaciones",
    "KEY_BOARD_Cant_Operac_Subtitle_income": "Expensas",
    "KEY_BOARD_Cant_Operac_Subtitle_expenses": "Gastos",
    "KEY_BOARD_SubsTitle": "Revisa la última informacion",
    // BUDGET
    "KEY_BUDGET_Name_Title": "Nombre Presupuesto ",
    "KEY_BUDGET_Date_Title": "Fecha Presupuesto",
    "KEY_BUDGET_Index_Title": "Presupuesto Indice",
    "KEY_BUDGET_Clean_Title": "Limpiar Presupuesto",
    "KEY_BUDGET_Empty_Title": "Vaciar Presupuesto",
    //STATISTICS
    "KEY_STATISTICS_Quant_Expenses_Graph_Title": "Grafico cantidad de Gastos",
    "KEY_STATISTICS_Quant_Income_Graph_Title": "Grafico cantidad de Ingresos",
    "KEY_STATISTICS_Percentages_Expenses_Graph_Title": "Grafico porcentajes de Ingresos",
    "KEY_STATISTICS_Percentages_Income_Graph_Title": "Grafico porcentajes de Ingresos",
    "KEY_STATISTICS_Price_Expenses_Graph_Title": "Grafico precios de Ingresos",
    "KEY_STATISTICS_Price_Income_Graph_Title": "Grafico precios de Ingresos",
    //MONEYS
    "KEY_MONEYS_Main_Title": "Cotizaciones",
    "KEY_MONEYS_Dolar_Title": "Cotizaciones Dolar ",
    "KEY_MONEYS_Real_Title": "Cotizaciones Real ",
    "KEY_MONEYS_Euro_Title": "Cotizaciones Euro ",
    "KEY_MONEYS_Last_act_Title": "Ultima act.",
    "KEY_MONEYS_sold_Subtitle": "Venta :  ",
    "KEY_MONEYS_buy_Subtitle": "Compra :  ",
    "KEY_MONEYS_variation_Subtitle": "Variación :  ",
    //REPORTS
    "KEY_REPORTS_Main_title": "Reportes",
    "KEY_REPORTS_Main_Subtitle": "Descarga la informacion necesaria",
    "KEY_REPORTS_Download_report_title": "Descargar reporte",
    //DATA
    "KEY_DATA_Cat_title": "Categorias",
    "KEY_DATA_Cat_Edit_subtitle": "Ver / Eliminar: ",
    "KEY_DATA_Cat_add_subtitle": "Agregar: ",
    "KEY_DATA_Payments_title": "Formas de Pago / Cobro",
    "KEY_DATA_Payments_Edit_subtitle": "Ver / Eliminar: ",
    "KEY_DATA_Payments_add_subtitle": "Agregar: ",
    "KEY_DATA_Cards_title": "Tarjetas",
    "KEY_DATA_Cards_Edit_subtitle": "Ver / Eliminar: ",
    "KEY_DATA_Cards_add_subtitle": "Agregar: ",
    "KEY_DATA_Banks_title": "Bancos",
    "KEY_DATA_Banks_Edit_subtitle": "Ver / Eliminar: ",
    "KEY_DATA_Banks_add_subtitle": "Agregar: ",
    //CONFIGURACION
    "KEY_CONFIGURATION_Languaje_title": "Idioma",
    "KEY_CONFIGURATION_Languaje_subtitle": "Seleccionar opcion",
    "KEY_CONFIGURATION_Theme_title": "Color",
    "KEY_CONFIGURATION_Theme_subtitle": "Seleccionar el color de tema",
    //INCOME
    "KEY_INCOME_Main_title": "Añadir",
    "KEY_INCOME_Add_item_subtitle": "Item: ",
    "KEY_INCOME_Add_value_subtitle": "Valor: ",
    "KEY_INCOME_Add_cat_subtitle": "Categoria: ",
    "KEY_INCOME_Add_payment_subtitle": "Forma de pago: ",
    "KEY_INCOME_Add_descrip_subtitle": "Descripcion: ",
    "KEY_INCOME_Add_save_subtitle": "Guardar",
    "KEY_INCOME_Graph_Title": "Grafico ingresos",
    "KEY_INCOME_LastList_Title": "Agregados recientes",
    "KEY_INCOME_CompleteList_Title": "Lista completa de ingresos",
    //EXPENSES
    "KEY_EXPENSES_Main_title": "Añadir",
    "KEY_EXPENSES_Add_item_subtitle": "Item: ",
    "KEY_EXPENSES_Add_value_subtitle": "Valor: ",
    "KEY_EXPENSES_Add_cat_subtitle": "Categoria: ",
    "KEY_EXPENSES_Add_payment_subtitle": "Forma de pago: ",
    "KEY_EXPENSES_Add_descrip_subtitle": "Descripcion: ",
    "KEY_EXPENSES_Add_save_subtitle": "Guardar",
    "KEY_EXPENSES_Graph_Title": "Grafico gastos",
    "KEY_EXPENSES_LastList_Title": "Agregados recientes",
    "KEY_EXPENSES_CompleteList_Title": "Lista completa de gastos",
    //ERROR
    "KEY_ERROR_Title": "Pagina no encontrada ",
}