translationFR = {
    // LIENS DE NAVIGATION
    "KEY_NAV_LINK_Board": "Conseil",
    "KEY_NAV_LINK_Budgets": "Budget",
    "KEY_NAV_LINK_Expenses": "Dépenses",
    "KEY_NAV_LINK_Income": "Revenu",
    "KEY_NAV_LINK_Statistics": "Statistiques",
    "KEY_NAV_LINK_Moneys": "Citations",
    "KEY_NAV_LINK_Reports": "Rapports",
    "KEY_NAV_LINK_Data": "Mes données",
    "KEY_NAV_LINK_Configuration": "Configuration",
    "KEY_NAV_LINK_Close_Session": "Fermer la session",
    // TAB SUP
    "KEY_Main_Title": "Principal",
    "KEY_Main_Gastos_acum": "Dépenses à payer",
    "KEY_Main_Ingresos_acum": "Revenu accumulé",
    "KEY_Main_Presp_disp": "Budget disponible",
    // CONSEIL
    "KEY_BOARD_Cant_Operac_Title": "Nombre d'opérations",
    "KEY_BOARD_Cant_Operac_Subtitle_income": "Dépenses",
    "KEY_BOARD_Cant_Operac_Subtitle_expenses": "Dépenses",
    "KEY_BOARD_SubsTitle": "Vérifiez les dernières informations",
    // BUDGET
    "KEY_BUDGET_Name_Title": "Nom du budget",
    "KEY_BUDGET_Date_Title": "Date du budget",
    "KEY_BUDGET_Index_Title": "Indice du budget",
    "KEY_BUDGET_Clean_Title": "Effacer le budget",
    "KEY_BUDGET_Empty_Title": "Budget vide",
    // STATISTIQUES
    "KEY_STATISTICS_Quant_Expenses_Graph_Title": "Montant graphique des dépenses",
    "KEY_STATISTICS_Quant_Income_Graph_Title": "Graphique du montant du revenu",
    "KEY_STATISTICS_Percentages_Expenses_Graph_Title": "Graphique des pourcentages de revenus",
    "KEY_STATISTICS_Percentages_Income_Graph_Title": "Graphique du pourcentage de revenu",
    "KEY_STATISTICS_Price_Expenses_Graph_Title": "Graphique du prix des revenus",
    "KEY_STATISTICS_Price_Income_Graph_Title": "Graphique du prix des revenus",
    // ARGENT
    "KEY_MONEYS_Main_Title": "Citations",
    "KEY_MONEYS_Dolar_Title": "Cotations en dollars",
    "KEY_MONEYS_Real_Title": "Real Quotes",
    "KEY_MONEYS_Euro_Title": "Citations en euros",
    "KEY_MONEYS_Last_act_Title": "Dernier acte.",
    "KEY_MONEYS_sold_Subtitle": "Vente:",
    "KEY_MONEYS_buy_Subtitle": "Achat:",
    "KEY_MONEYS_variation_Subtitle": "Variante:",
    // RAPPORTS
    "KEY_REPORTS_Main_title": "Rapports",
    "KEY_REPORTS_Main_Subtitle": "Téléchargez les informations nécessaires",
    "KEY_REPORTS_Download_report_title": "Télécharger le rapport",
    //LES DONNÉES
    "KEY_DATA_Cat_title": "Catégories",
    "KEY_DATA_Cat_Edit_subtitle": "Afficher / Supprimer:",
    "KEY_DATA_Cat_add_subtitle": "Ajouter:",
    "KEY_DATA_Payments_title": "Modes de paiement / recouvrement",
    "KEY_DATA_Payments_Edit_subtitle": "Afficher / Supprimer:",
    "KEY_DATA_Payments_add_subtitle": "Ajouter:",
    "KEY_DATA_Cards_title": "Cartes",
    "KEY_DATA_Cards_Edit_subtitle": "Afficher / Supprimer:",
    "KEY_DATA_Cards_add_subtitle": "Ajouter:",
    "KEY_DATA_Banks_title": "Banques",
    "KEY_DATA_Banks_Edit_subtitle": "Afficher / Supprimer:",
    "KEY_DATA_Banks_add_subtitle": "Ajouter:",
    //RÉGLAGE
    "KEY_CONFIGURATION_Languaje_title": "Langue",
    "KEY_CONFIGURATION_Languaje_subtitle": "Sélectionner une option",
    "KEY_CONFIGURATION_Theme_title": "Couleur",
    "KEY_CONFIGURATION_Theme_subtitle": "Sélectionnez la couleur du thème",
    // LE REVENU
    "KEY_INCOME_Main_title": "Ajouter",
    "KEY_INCOME_Add_item_subtitle": "Élément:",
    "KEY_INCOME_Add_value_subtitle": "Valeur:",
    "KEY_INCOME_Add_cat_subtitle": "Catégorie:",
    "KEY_INCOME_Add_payment_subtitle": "Mode de paiement:",
    "KEY_INCOME_Add_descrip_subtitle": "Description:",
    "KEY_INCOME_Add_save_subtitle": "Enregistrer",
    "KEY_INCOME_Graph_Title": "Graphique des revenus",
    "KEY_INCOME_LastList_Title": "Ajouts récents",
    "KEY_INCOME_CompleteList_Title": "Liste complète des entrées",
    // DÉPENSES
    "KEY_EXPENSES_Main_title": "Ajouter",
    "KEY_EXPENSES_Add_item_subtitle": "Item:",
    "KEY_EXPENSES_Add_value_subtitle": "Valeur:",
    "KEY_EXPENSES_Add_cat_subtitle": "Catégorie:",
    "KEY_EXPENSES_Add_payment_subtitle": "Mode de paiement:",
    "KEY_EXPENSES_Add_descrip_subtitle": "Description:",
    "KEY_EXPENSES_Add_save_subtitle": "Enregistrer",
    "KEY_EXPENSES_Graph_Title": "Graphique des dépenses",
    "KEY_EXPENSES_LastList_Title": "Ajouts récents",
    "KEY_EXPENSES_CompleteList_Title": "Liste complète des dépenses",
    //ERREUR
    "KEY_ERROR_Title": "Page non trouvée",
}