translationPT = {
    // NAV LINKS
    "KEY_NAV_LINK_Board": "Board",
    "KEY_NAV_LINK_Budgets": "Orçamento",
    "KEY_NAV_LINK_Expenses": "Despesas",
    "KEY_NAV_LINK_Income": "Renda",
    "KEY_NAV_LINK_Statistics": "Estatísticas",
    "KEY_NAV_LINK_Moneys": "Quotes",
    "KEY_NAV_LINK_Reports": "Relatórios",
    "KEY_NAV_LINK_Data": "Meus dados",
    "KEY_NAV_LINK_Configuration": "Configuração",
    "KEY_NAV_LINK_Close_Session": "Fechar sessão",
    // TAB SUP
    "KEY_Main_Title": "Principal",
    "KEY_Main_Gastos_acum": "Despesas acumuladas",
    "KEY_Main_Ingresos_acum": "Renda acumulada",
    "KEY_Main_Presp_disp": "Orçamento disponível",
    // BORDA
    "KEY_BOARD_Cant_Operac_Title": "Número de operações",
    "KEY_BOARD_Cant_Operac_Subtitle_income": "Despesas",
    "KEY_BOARD_Cant_Operac_Subtitle_expenses": "Despesas",
    "KEY_BOARD_SubsTitle": "Verifique as informações mais recentes",
    // DESPESAS
    "KEY_BUDGET_Name_Title": "Nome do orçamento",
    "KEY_BUDGET_Date_Title": "Data do orçamento",
    "KEY_BUDGET_Index_Title": "Índice de orçamento",
    "KEY_BUDGET_Clean_Title": "Limpar orçamento",
    "KEY_BUDGET_Empty_Title": "Orçamento vazio",
    // ESTATISTICAS
    "KEY_STATISTICS_Quant_Expenses_Graph_Title": "Valor gráfico das despesas",
    "KEY_STATISTICS_Quant_Income_Graph_Title": "Gráfico do valor da receita",
    "KEY_STATISTICS_Percentages_Expenses_Graph_Title": "Gráfico de porcentagens de renda",
    "KEY_STATISTICS_Percentages_Income_Graph_Title": "Gráfico de porcentagem de renda",
    "KEY_STATISTICS_Price_Expenses_Graph_Title": "Gráfico de preço de renda",
    "KEY_STATISTICS_Price_Income_Graph_Title": "Gráfico de preço de renda",
    // DINHEIROS
    "KEY_MONEYS_Main_Title": "Citações",
    "KEY_MONEYS_Dolar_Title": "Cotações em dólares",
    "KEY_MONEYS_Real_Title": "Citações reais",
    "KEY_MONEYS_Euro_Title": "Euro Quotes",
    "KEY_MONEYS_Last_act_Title": "Último ato.",
    "KEY_MONEYS_sold_Subtitle": "Promoção:",
    "KEY_MONEYS_buy_Subtitle": "Compra:",
    "KEY_MONEYS_variation_Subtitle": "Variação:",
    // RELATÓRIOS
    "KEY_REPORTS_Main_title": "Relatórios",
    "KEY_REPORTS_Main_Subtitle": "Baixe as informações necessárias",
    "KEY_REPORTS_Download_report_title": "Baixar relatório",
    //DADOS
    "KEY_DATA_Cat_title": "Categorias",
    "KEY_DATA_Cat_Edit_subtitle": "Exibir / Excluir:",
    "KEY_DATA_Cat_add_subtitle": "Adicionar:",
    "KEY_DATA_Payments_title": "Métodos de pagamento / cobrança",
    "KEY_DATA_Payments_Edit_subtitle": "Ver / Excluir:",
    "KEY_DATA_Payments_add_subtitle": "Adicionar:",
    "KEY_DATA_Cards_title": "Cartões",
    "KEY_DATA_Cards_Edit_subtitle": "Exibir / Excluir:",
    "KEY_DATA_Cards_add_subtitle": "Adicionar:",
    "KEY_DATA_Banks_title": "Bancos",
    "KEY_DATA_Banks_Edit_subtitle": "Exibir / Excluir:",
    "KEY_DATA_Banks_add_subtitle": "Adicionar:",
    //CONTEXTO
    "KEY_CONFIGURATION_Languaje_title": "Idioma",
    "KEY_CONFIGURATION_Languaje_subtitle": "Selecione a opção",
    "KEY_CONFIGURATION_Theme_title": "Cor",
    "KEY_CONFIGURATION_Theme_subtitle": "Selecione a cor do tema",
    // RENDA
    "KEY_INCOME_Main_title": "Adicionar",
    "KEY_INCOME_Add_item_subtitle": "Item:",
    "KEY_INCOME_Add_value_subtitle": "Valor:",
    "KEY_INCOME_Add_cat_subtitle": "Categoria:",
    "KEY_INCOME_Add_payment_subtitle": "Método de pagamento:",
    "KEY_INCOME_Add_descrip_subtitle": "Descrição:",
    "KEY_INCOME_Add_save_subtitle": "Salvar",
    "KEY_INCOME_Graph_Title": "Gráfico de renda",
    "KEY_INCOME_LastList_Title": "Adições recentes",
    "KEY_INCOME_CompleteList_Title": "Lista completa de entradas",
    // DESPESAS
    "KEY_EXPENSES_Main_title": "Adicionar",
    "KEY_EXPENSES_Add_item_subtitle": "Item:",
    "KEY_EXPENSES_Add_value_subtitle": "Valor:",
    "KEY_EXPENSES_Add_cat_subtitle": "Categoria:",
    "KEY_EXPENSES_Add_payment_subtitle": "Método de pagamento:",
    "KEY_EXPENSES_Add_descrip_subtitle": "Descrição:",
    "KEY_EXPENSES_Add_save_subtitle": "Salvar",
    "KEY_EXPENSES_Graph_Title": "Gráfico de despesas",
    "KEY_EXPENSES_LastList_Title": "Adições recentes",
    "KEY_EXPENSES_CompleteList_Title": "Lista completa de despesas",
    //ERRO
    "KEY_ERROR_Title": "Página não encontrada",


}